framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
#    csrf_protection: ~

    session:
        # With this config, PHP's native session handling is used
        handler_id: ~

    fragments: ~
    php_errors:
        log: true