app_main:
    path: /
    controller: App\Controller\CoinController::index

app_subscribe:
    path: /subscribe
    controller: App\Controller\SubscriptionController::create

app_exchanges_list:
    path: /exchanges
    controller: App\Controller\ExchangeController::index

app_exchanges_show:
    path: /exchanges/{id}
    controller: App\Controller\ExchangeController::show
