# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

#   Custom services
    coimarketcap.client:
       alias: eight_points_guzzle.client.api_coinmarketcap
    coinbase.client:
       alias: eight_points_guzzle.client.api_exchange_gdax
    bittrex.client:
       alias: eight_points_guzzle.client.api_exchange_bittrex

    App\Command\CoinFetcher:
        arguments: ['@App\Repository\CoinRepository', '@coimarketcap.client', '@Doctrine\ORM\EntityManagerInterface']
        autowire: false

#   Exchanges
    App\Services\Exchanges\CoinBase:
        arguments: ['@coinbase.client']
        autowire: false
    App\Services\Exchanges\Bittrex:
        arguments: ['@bittrex.client']
        autowire: false

#   Utils
    App\Utils\ExchangeMapper:
        arguments: ['@App\Services\Exchanges\CoinBase', '@App\Services\Exchanges\Bittrex']
        autowire: false